name: Course Reminder
on:
  schedule:
    # 北京时间每天 7:00-22:55，每5分钟运行一次（UTC时间需要-8小时）
    - cron: '*/5 23-23,0-14 * * *'  # UTC时间23:00-14:00（对应北京时间7:00-22:00）
  workflow_dispatch:        # 允许手动触发

jobs:
  check-schedule:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pytz  # 添加时区支持

    - name: Run reminder check
      env:
        TZ: Asia/Shanghai            # 设置时区为北京时间
        WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}
        WXPUSHER_TOPIC_ID: ${{ secrets.WXPUSHER_TOPIC_ID }}
      run: python main.py
