name: Course Reminder
on:
  schedule:
    # 拆分两个 cron 表达式确保全覆盖
    - cron: '*/5 23 * * *'     # UTC 23:00-23:55（北京时间 7:00-7:55）
    - cron: '*/5 0-14 * * *'   # UTC 0:00-14:55（北京时间 8:00-22:55）
  workflow_dispatch:

jobs:
  check-schedule:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pytz

    - name: Run reminder check
      env:
        TZ: Asia/Shanghai
        WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}
        WXPUSHER_TOPIC_ID: ${{ secrets.WXPUSHER_TOPIC_ID }}
      run: python main.py
